// Code generated by Google Apps Script, DO NOT EDIT.
namespace Config
{
	public class Tables
	{
		public TbTestcfg TbTestcfg { get; private set; }
		public TbTest2 TbTest2 { get; private set; }
		public TbTest3 TbTest3 { get; private set; }

		public Tables(System.Func<string, string> loader)
		{
			TbTestcfg = new TbTestcfg(loader("Testcfg"));
			TbTest2 = new TbTest2(loader("Test2"));
			TbTest3 = new TbTest3(loader("Test3"));
		}
	}
}
