// Code generated by Google Apps Script, DO NOT EDIT.
namespace Config
{
	public class Tables
	{
		public TbCharacterConfig TbCharacterConfig { get; private set; }
		public TbEquipmentConfig TbEquipmentConfig { get; private set; }
		public TbCharacterSkillsConfig TbCharacterSkillsConfig { get; private set; }

		public Tables(System.Func<string, string> loader)
		{
			TbCharacterConfig = new TbCharacterConfig(loader("CharacterConfig"));
			TbEquipmentConfig = new TbEquipmentConfig(loader("EquipmentConfig"));
			TbCharacterSkillsConfig = new TbCharacterSkillsConfig(loader("CharacterSkillsConfig"));
		}
	}
}
